# Generated by Django 5.0.9 on 2024-11-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tomorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('warm', models.BooleanField()),
                ('sunny', models.BooleanField()),
                ('windy', models.BooleanField()),
            ],
        ),
    ]
