# Generated by Django 5.0.9 on 2024-11-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_start', models.DateTimeField()),
                ('belief_horizon_in_seconds', models.IntegerField()),
                ('event_value', models.FloatField()),
                ('sensor', models.CharField(choices=[('temperature', 'Temperature'), ('wind_speed', 'Wind Speed'), ('irradiance', 'Irradiance')], max_length=20)),
                ('unit', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-event_start', 'belief_horizon_in_seconds'],
            },
        ),
    ]
